
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int FUNCTION = 54;
  public static final int L_FATHERCHRISTMAS = 30;
  public static final int FINREGALO = 50;
  public static final int HADA = 41;
  public static final int KRISKRINGLE = 25;
  public static final int PERSONA = 21;
  public static final int DANCER = 4;
  public static final int DUENDE = 42;
  public static final int CIERRECUENTO = 35;
  public static final int RUDOLPH = 2;
  public static final int ENTREGA = 52;
  public static final int CIERRAREGALO = 39;
  public static final int ABREEMPAQUE = 36;
  public static final int NARRA = 48;
  public static final int PERENOEL = 23;
  public static final int MAIN = 53;
  public static final int HACE = 44;
  public static final int ENVUELVE = 43;
  public static final int PEPPERMINT = 15;
  public static final int PAPANOEL = 27;
  public static final int GRINCH = 9;
  public static final int EOF = 0;
  public static final int JINGLE = 13;
  public static final int CORTA = 47;
  public static final int SANTACLAUS = 22;
  public static final int MELCHOR = 17;
  public static final int REVISA = 45;
  public static final int error = 1;
  public static final int COMA = 51;
  public static final int HERMEY = 11;
  public static final int BALTASAR = 19;
  public static final int GASPAR = 18;
  public static final int ABRECUENTO = 34;
  public static final int ESCUCHA = 49;
  public static final int ABREREGALO = 38;
  public static final int PRANCER = 5;
  public static final int CIERREEMPAQUE = 37;
  public static final int DASHER = 3;
  public static final int L_KRISKRINGLE = 31;
  public static final int ENVIA = 46;
  public static final int L_PERENOEL = 29;
  public static final int JANGLE = 14;
  public static final int DEDMOROZ = 26;
  public static final int L_PAPANOEL = 33;
  public static final int CUPID = 8;
  public static final int COMET = 7;
  public static final int BUDDY = 12;
  public static final int ELFO = 40;
  public static final int LOCAL = 20;
  public static final int WUNORSE = 16;
  public static final int FATHERCHRISTMAS = 24;
  public static final int VIXEN = 6;
  public static final int QUIEN = 10;
  public static final int L_SANTACLAUS = 28;
  public static final int L_DEDMOROZ = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RUDOLPH",
  "DASHER",
  "DANCER",
  "PRANCER",
  "VIXEN",
  "COMET",
  "CUPID",
  "GRINCH",
  "QUIEN",
  "HERMEY",
  "BUDDY",
  "JINGLE",
  "JANGLE",
  "PEPPERMINT",
  "WUNORSE",
  "MELCHOR",
  "GASPAR",
  "BALTASAR",
  "LOCAL",
  "PERSONA",
  "SANTACLAUS",
  "PERENOEL",
  "FATHERCHRISTMAS",
  "KRISKRINGLE",
  "DEDMOROZ",
  "PAPANOEL",
  "L_SANTACLAUS",
  "L_PERENOEL",
  "L_FATHERCHRISTMAS",
  "L_KRISKRINGLE",
  "L_DEDMOROZ",
  "L_PAPANOEL",
  "ABRECUENTO",
  "CIERRECUENTO",
  "ABREEMPAQUE",
  "CIERREEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "NARRA",
  "ESCUCHA",
  "FINREGALO",
  "COMA",
  "ENTREGA",
  "MAIN",
  "FUNCTION"
  };
}

