package com.compi;

import java_cup.runtime.*;

class Parser;

terminal PLUS, TIMES, LPAREN, RPAREN;
terminal Integer NUMBER;

non terminal Integer expr;

/* Precedencia */
precedence left PLUS;
precedence left TIMES;

start with expr;

expr ::= expr:e1 PLUS expr:e2   {: RESULT = e1 + e2; :}
        | expr:e1 TIMES expr:e2 {: RESULT = e1 * e2; :}
        | LPAREN expr:e RPAREN  {: RESULT = e; :}
        | NUMBER:n              {: RESULT = n; :};